### ISSUE TITLE
Android Tests and View Model Events

### ISSUE THREAD

**Issue by eugenio1590** [etiennelenhart/Eiffel#126]
Hi @etiennelenhart , I have a question about the instrumented tests and the events into viewmodels. I have a LiveData object into my ViewModel when this variable is null a need to redirect automatically to another activity. I create an event to manage it. This is worked very well with the following code:

````
viewModel.observeState(this) { state ->
            state.event?.peek {
                when(it) {
                    is ViewEvent.NullRecipe -> {
                        startActivity<CreateRecipeActivity>()
                        true
                    }
                }
            }
        }

````

Of course, this happens when the activity is created. So, I need to wait for the event to check if the CreateRecipeActivity is created. But espresso test fails, I suppose the event is not fired yet. Anything idea to tests it? If the new version (5.0.0) has support for that, please let me know. Thanks.

**Comment by etiennelenhart** [comment]
Hey @eugenio1590, thanks for your question.

Could you maybe show me a snippet of your failing Espresso test? It sounds like you're trying to test whether the `CreateRecipeActivity` is displayed when the original Activity is started with a null Recipe.
Since `LiveData` and therefore `Events` are inherently asynchronous, you probably have to wait for the Event and then check for the created Activity.
That may be a bit tricky and I think I'll be better able to help when seeing what exactly you're trying to accomplish.

**Comment by eugenio1590** [comment]
Hi @etiennelenhart I fixed it by checking the activity title. I had thought of using `intended` function of Espresso but when the activity is created has no `intents` towards another activity. Of course, I need to wait for the current activity is created, in this case: `CreateRecipeActivity`. So, I can check the title of the current activity using the following code:

````
class InvalidRecipeTest : AbstractApplicationTest<MainActivity>(), KoinTest {

    private val recipesDataSource = mockk<RecipesDataSource> {
        every { recipes } returns null
    }

    @get:Rule
    val activityRule = object : IntentsTestRule<MainActivity>(MainActivity::class.java) {
        override fun beforeActivityLaunched() {
            super.beforeActivityLaunched()
            val recipesModule = module { factory(override = true) { recipesDataSource } }
            loadKoinModules(recipesModule )
        }
    }

    @Test
    fun redirectToCreateRecipeScreen() {
        onView(allOf(withText(R.string.activity_create_recipe), withParent(isAssignableFrom(Toolbar::class.java))))
            .check(matches(withEffectiveVisibility(Visibility.VISIBLE)))
    }

}
````

It is not the result that I expected but It is worked.

**Comment by etiennelenhart** [comment]
Ah, I'm not really an Espresso expert so I don't know if there's a better way to test this. But as this seems to be more of an issue with Espresso if anything and not Eiffel I'll close this for now.
