### ISSUE TITLE
Debugging mode

### ISSUE THREAD

**Issue by etiennelenhart** [etiennelenhart/Eiffel#60]
For easier debugging `EiffelViewModel` should provide a `debug` flag that logs all `Action` dispatches and `State` updates.

**Comment by jordond** [comment]
[Here](https://github.com/ww-tech/roxie/wiki/7.-Logging) is a similar library that has logging of the actions/reducer.  They enable logging via a static method, with the ability to add a custom logger.

Not sure how you were planning on implementing the logging, but here i one approach.

**Comment by etiennelenhart** [comment]
I was planning to add a boolean "debug" parameter in `EiffelViewModel` so debug mode could be enabled per view model.

An additional static configuration to globally disable logging seems like a good idea.

Thanks for the suggestion.

**Comment by etiennelenhart** [comment]
Resolved by #72.
