### ISSUE TITLE
State not updating with new but similar ViewEvent

### ISSUE THREAD

**Issue by jordond** [etiennelenhart/Eiffel#90]
I've run into an issue, and was curious about your thoughts on it.

What's happening is I have a button that dispatches an action, which updates the state with a `ViewEvent` for navigating to the next screen.  Now if the user hits the back button, and tries to click the button again.  The state won't update because it is blocked by the [equality test](https://github.com/etiennelenhart/Eiffel/blob/master/eiffel/src/main/java/com/etiennelenhart/eiffel/viewmodel/EiffelViewModel.kt#L121).  Because the`ViewEvents` are technically the same (even though the previous one was `handled`).

My use-case is for creating Navigation commands, but I have written a simple test that showcases a more basic example:

```kotlin
data class TestViewEvent(val value: Int) : ViewEvent()

data class ViewEventState(val viewEvent: TestViewEvent? = null) : State

data class DoTestEvent(val data: Int) : Action

val viewEventUpdate = update<ViewEventState, DoTestEvent> { copy(viewEvent = TestViewEvent(it.data)) }

@Test
fun `GIVEN EiffelViewModel subclass WHEN handled 'ViewEvent' dispatched multiple times THEN state is updated`() {
    @UseExperimental(ExperimentalCoroutinesApi::class)
    val viewModel =
        object : EiffelViewModel<ViewEventState, DoTestEvent>(ViewEventState(), Dispatchers.Unconfined) {
            override val update = viewEventUpdate
            override val interceptionDispatcher = Dispatchers.Unconfined
        }

    var actual = 0
    viewModel.state.observeForever { state ->
        state.viewEvent?.peek {
            actual++
            true
        }
    }

    // Succeeds
    viewModel.dispatch(DoTestEvent(42))
    viewModel.dispatch(DoTestEvent(24))
    assertEquals(2, actual) // actual: 2

    actual = 0

    // Fails
    viewModel.dispatch(DoTestEvent(42))
    viewModel.dispatch(DoTestEvent(42))
    assertEquals(2, actual) // actual: 1
}
```

**Comment by etiennelenhart** [comment]
Good catch! I actually haven't tested `ViewEvent` together with `EiffelViewModel` yet.

I'm currently thinking about making it possible to return `null` in `Update` to signal that the `State` hasn't been modified but this may result in the same state being emitted multiple times if an update is signaled but `copy` didn't actually change any values. (May happen occasionally, especially with `LiveData` sources.)

As another solution we maybe could override `equals` to include the `handled` property of `ViewEvent` but I'm not sure if that works.

**Comment by jordond** [comment]
I tried overriding the `equals` but it was still failing for me. But I don't know enough about kotlin/java's equality checks to be confident that it doesn't work.

I'll continue brainstorming.

**Comment by jordond** [comment]
Btw here's my findings.  I modified `ViewEvent`:

```kotlin
abstract class ViewEvent {

    internal var handled = false

    override fun equals(other: Any?): Boolean {
        if (other !is ViewEvent) return false

        return this::class == other::class && other.handled == handled
    }

    override fun hashCode(): Int = Arrays.hashCode(arrayOf(this::class, handled))
}
```

But the test *still* failed unless I added the `equals` and `hashcode` to the `TestViewEvent`:

```kotlin
data class TestViewEvent(val value: Int) : ViewEvent() {

    override fun equals(other: Any?): Boolean = super.equals(other)

    override fun hashCode(): Int = super.hashCode()
}
```

Then the test passes.  But it seems kind of annoying to call the `super` functions for each `ViewEvent` that's created.

**Comment by jordond** [comment]
Ah, so If you make the `TestViewEvent` a regular `class` instead of a `data class`, then the `equals` from `ViewEvent` will work.  From the kotlin docs on [data classes](https://kotlinlang.org/docs/reference/data-classes.html).
